apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    name: pv001
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /data/volumes1
    server: 192.168.107.89
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
    name: pv002
spec:
  accessModes: 
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data/volumes2
    server: 192.168.107.89
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
  labels:
    name: pv003
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 15Gi
  nfs:
    path: /data/volumes3
    server: 192.168.107.89
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
  labels:
    name: pv004
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /data/volumes4
    server: 192.168.107.89
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv005
  labels:
    name: pv005
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 25Gi
  nfs:
    path: /data/volumes5
    server: 192.168.107.8
